site_name: Gyro Kobra Go Mods

theme:
  name: material
  palette:
    primary: blue
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.expand
    - navigation.path
    - navigation.instant

use_directory_urls: false

nav:
    - Home: index.md
    - Mods:
      - Enclosure: mods/enclosure.md
      - Motherboard Swap: mods/motherboard-swap.md
      - Silicone Spacers: mods/silicone-spacers.md
      - Bowden Tube: mods/bowden-tubing.md
      - Print Heads: mods/print-heads.md
      - Buck Converters: mods/buck-converters.md
      - Belted Z-Axis: mods/belted-z-axis.md
      - Oribter 2.0: mods/orbiter-2.md
      - MicroSwiss Hotend: mods/microswiss-hotend.md
      - Arctic 25X40 Fan: mods/arctic-40mm.md
      - Metal Tensioners: mods/metal-tensioners.md
    - Software:
      - Intro: software/intro.md
      - Klipper: software/klipper.md
      - Octoprint: software/octoprint.md
    - Compatible Kits: compat_kits.md
    - Accessories: 
      - Intro: accessories/intro.md
      - Camera: accessories/raspi_cam.md
      - Motherboard: accessories/skr3.md
      - Hero Me Gen. 7.1: accessories/hmg7.md
    - 3D Models: 3d_models.md
    - Before & After: comparison.md
    - About: about.md

markdown_extensions:
  - admonition
  - codehilite
  - smarty
  - meta
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: True

repo_url: https://github.com/Gyrohammer/KGM
repo_name: gyrohammer/KGM