site_name: Gyro Kobra Go Mods

theme:
  name: material
  langage: en
  
  features: 
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - header.autohide
    - content.code.copy
  
  logo: assets/logo.png
  favicon: assets/favicon.png
  
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb
        #primary: blue grey
        name: Toggle dark mode
        
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        #primary: slate
        name: Toggle light mode

use_directory_urls: false

nav:
    - Home: index.md
    - Easy Mods: mods/easy-mods.md
    - Advanced Mods:
      - Enlcosure: mods/enclosure.md
      - Motherboard: mods/motherboard-swap.md
      - Print Head: mods/print-heads.md
      - Arctic 25X40 Fan: mods/arctic-40mm.md
      - Belted Z-Axis: mods/belted-z-axis.md
      - Oribter 2.0: mods/orbiter-2.md

    - Klipper: software/klipper.md
    - About: about.md

markdown_extensions:
  - admonition
  - codehilite
  - smarty
  - meta
  - attr_list
  - md_in_html
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: True

repo_url: https://github.com/Gyrohammer/KGM
repo_name: gyrohammer/KGM